name: Update top10 IP list

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点执行（可根据你需求调整）
  workflow_dispatch:      # 允许手动触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    env:
      IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}  # 从 Secrets 中读取 token，避免明文

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add top10.txt
          git commit -m "Auto-update top10.txt" || echo "No changes to commit"
          git push
